Now using oh-my-zsh. Still to debug a few performance problems.
--HG--
rename : shell/aliases => shell/custom-configs/aliases
rename : shell/env => shell/custom-configs/env
rename : shell/sjl-z.sh => shell/custom-configs/sjl-z.sh
rename : shell/zsh-syntax-highlighting.zsh => shell/custom-configs/zsh-syntax-highlighting.zsh

diff --git a/nautilus-scripts/Diff/Meld b/nautilus-scripts/Diff/Meld
--- a/nautilus-scripts/Diff/Meld
+++ b/nautilus-scripts/Diff/Meld
@@ -1,4 +1,11 @@
 #!/bin/bash
 
+if [ -z `which meld` ] ; then
+    zenity --error --text="meld not found!
+
+Please install meld."
+    exit 1
+fi
+
 meld $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
 
